### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by abcdefghijorngarbosaxyz** [ArthurIvanov/feather-icons-react-typescript#14]
Hello. I'm getting this error when compiling 

![Image](https://user-images.githubusercontent.com/19945743/195437550-3ebc800a-238d-40fe-a8f2-fc58b808580e.PNG)

index.tsx

`import { Icon } from "@ailibs/feather-react-ts";`
`...`
`<Icon name="sidebar" />`

**Comment by ArthurIvanov** [comment]
> Hello. I'm getting this error when compiling
> 
> ![Image](https://user-images.githubusercontent.com/19945743/195437550-3ebc800a-238d-40fe-a8f2-fc58b808580e.PNG)
> 
> index.tsx
> 
> `import { Icon } from "@ailibs/feather-react-ts";` `...` `<Icon name="sidebar" />`

Hello, can you please send link to your repo, ill take a look where problem is.
Thanks.
